# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanTestForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scanTestForm(object):
    def setupUi(self, scanTestForm):
        scanTestForm.setObjectName("scanTestForm")
        scanTestForm.resize(317, 251)
        self.pbtGetBarcode = QtWidgets.QPushButton(scanTestForm)
        self.pbtGetBarcode.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pbtGetBarcode.setObjectName("pbtGetBarcode")
        self.tbResult = QtWidgets.QTextBrowser(scanTestForm)
        self.tbResult.setGeometry(QtCore.QRect(30, 40, 256, 192))
        self.tbResult.setObjectName("tbResult")

        self.retranslateUi(scanTestForm)
        QtCore.QMetaObject.connectSlotsByName(scanTestForm)

    def retranslateUi(self, scanTestForm):
        _translate = QtCore.QCoreApplication.translate
        scanTestForm.setWindowTitle(_translate("scanTestForm", "扫码枪对焦测试"))
        self.pbtGetBarcode.setText(_translate("scanTestForm", "扫码"))
