# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnlockForm(object):
    def setupUi(self, UnlockForm):
        UnlockForm.setObjectName("UnlockForm")
        UnlockForm.resize(238, 142)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        UnlockForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UnlockForm.setWindowIcon(icon)
        UnlockForm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.layoutWidget = QtWidgets.QWidget(UnlockForm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 194, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cbRole = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.cbRole.setFont(font)
        self.cbRole.setObjectName("cbRole")
        self.cbRole.addItem("")
        self.cbRole.addItem("")
        self.gridLayout.addWidget(self.cbRole, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.leOperatorId = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.leOperatorId.setFont(font)
        self.leOperatorId.setObjectName("leOperatorId")
        self.gridLayout.addWidget(self.leOperatorId, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lePassword = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.lePassword.setFont(font)
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.gridLayout.addWidget(self.lePassword, 2, 1, 1, 2)
        self.pbtLogin = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.pbtLogin.setFont(font)
        self.pbtLogin.setObjectName("pbtLogin")
        self.gridLayout.addWidget(self.pbtLogin, 3, 0, 1, 2)
        self.pbtExit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        self.pbtExit.setFont(font)
        self.pbtExit.setObjectName("pbtExit")
        self.gridLayout.addWidget(self.pbtExit, 3, 2, 1, 1)

        self.retranslateUi(UnlockForm)
        QtCore.QMetaObject.connectSlotsByName(UnlockForm)

    def retranslateUi(self, UnlockForm):
        _translate = QtCore.QCoreApplication.translate
        UnlockForm.setWindowTitle(_translate("UnlockForm", "解除报警"))
        self.cbRole.setItemText(0, _translate("UnlockForm", "技术员"))
        self.cbRole.setItemText(1, _translate("UnlockForm", "工程师"))
        self.label.setText(_translate("UnlockForm", "工号："))
        self.label_2.setText(_translate("UnlockForm", "密码："))
        self.pbtLogin.setText(_translate("UnlockForm", "登录"))
        self.pbtExit.setText(_translate("UnlockForm", "取消"))
